# Generated by Django 4.2.16 on 2026-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPNSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField()),
                ("remnawave_uuid", models.CharField(max_length=36)),
                ("remnawave_short_id", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=100)),
                ("subscription_url", models.URLField(max_length=500)),
                ("expire_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
