# Generated by Django 4.2.16 on 2026-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VPNSubscription",
        ),
    ]
