# Generated by Django 4.2.16 on 2026-05-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("connect", "0002_delete_vpnsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proxy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Proxy Name"
                    ),
                ),
                (
                    "connection_url",
                    models.TextField(
                        verbose_name="Connection URL (vless://, ss://, etc.)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Proxy",
                "verbose_name_plural": "Proxies",
            },
        ),
    ]
