# Generated by Django 4.2.16 on 2026-05-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Порт"
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="secret",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Секрет (для MTProxy)",
            ),
        ),
        migrations.AddField(
            model_name="proxy",
            name="server",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Сервер (host)",
            ),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="connection_url",
            field=models.TextField(
                help_text="Например: https://t.me/proxy?server=...&port=...&secret=...",
                verbose_name="Ссылка для подключения",
            ),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="proxy",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Название прокси"
            ),
        ),
    ]
