# Generated by Django 4.2.16 on 2026-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0004_proxy_port_proxy_secret_proxy_server_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_id",
                    models.IntegerField(
                        unique=True, verbose_name="ID Ноды (Remnawave)"
                    ),
                ),
                (
                    "status_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Статус сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус сервера",
                "verbose_name_plural": "Статусы серверов",
            },
        ),
    ]
