# Generated by Django 4.2.16 on 2026-05-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0005_nodestatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodestatus",
            name="node_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="ID Ноды (Remnawave)"
            ),
        ),
    ]
