# Generated by Django 4.2.16 on 2026-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0006_alter_nodestatus_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodestatus",
            name="manual_is_online",
            field=models.BooleanField(
                default=True, verbose_name="Статус онлайн (вручную)"
            ),
        ),
        migrations.AddField(
            model_name="nodestatus",
            name="use_manual_status",
            field=models.BooleanField(
                default=False, verbose_name="Ручное управление"
            ),
        ),
    ]
