# Generated by Django 4.2.16 on 2026-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0007_nodestatus_manual_is_online_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodestatus",
            name="last_alert_sent",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Последнее отправленное уведомление",
            ),
        ),
        migrations.AddField(
            model_name="nodestatus",
            name="last_known_online",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Последнее известное состояние (онлайн)",
            ),
        ),
    ]
