# Generated by Django 4.2.16 on 2026-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="device_limit",
            field=models.IntegerField(default=1),
        ),
    ]
