# Generated by Django 4.2.16 on 2026-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_tariff_device_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="squad_name",
            field=models.CharField(default="Test-squad", max_length=100),
        ),
    ]
