# Generated by Django 4.2.16 on 2026-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_tariff_squad_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariff",
            name="squad_name",
        ),
        migrations.AddField(
            model_name="tariff",
            name="squad_uuid",
            field=models.CharField(
                default="b8a6e550-7f4d-4300-b675-abb3d762b078", max_length=100
            ),
        ),
    ]
