# Generated by Django 4.2.16 on 2026-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_tariff_squad_name_tariff_squad_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="squad_uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
