# Generated by Django 4.2.16 on 2026-05-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_tariff_squad_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="has_proxy_bypass",
            field=models.BooleanField(default=False, verbose_name="Proxy"),
        ),
    ]
