# Generated by Django 4.2.16 on 2026-05-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_tariff_has_proxy_bypass"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("PURCHASE", "Purchase"), ("TOPUP", "Top-up")],
                default="PURCHASE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.tariff",
            ),
        ),
    ]
