# Generated by Django 4.2.16 on 2026-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0007_nodestatus_manual_is_online_and_more"),
        ("shop", "0007_order_amount_order_order_type_alter_order_tariff"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="proxies",
            field=models.ManyToManyField(
                blank=True,
                related_name="tariffs",
                to="connect.proxy",
                verbose_name="Доступные прокси",
            ),
        ),
    ]
