# Generated by Django 4.2.16 on 2026-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_promo_code_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("CHARGEBACK", "Chargeback"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
