# Generated by Django 4.2.16 on 2026-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="whitelist_squad_uuid",
            field=models.CharField(
                blank=True,
                help_text="Squad UUID для whitelist-подписки (обход белых списков). Заполнять только если has_proxy_bypass=True.",
                max_length=100,
                null=True,
                verbose_name="Whitelist Squad UUID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("TOPUP", "Top-up"),
                    ("WHITELIST_TOPUP", "Whitelist Traffic Top-up"),
                ],
                default="PURCHASE",
                max_length=20,
            ),
        ),
    ]
