# Generated by Django 4.2.16 on 2026-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_add_whitelist_sub_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="has_whitelist",
            field=models.BooleanField(
                default=False, verbose_name="VPN с обходом белых списков"
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="whitelist_squad_uuid",
            field=models.CharField(
                blank=True,
                help_text="Squad UUID для whitelist-подписки (обход белых списков). Заполнять только если has_whitelist=True.",
                max_length=100,
                null=True,
                verbose_name="Whitelist Squad UUID",
            ),
        ),
    ]
