# Generated by Django 4.2.16 on 2026-07-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_tariff_has_whitelist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariff",
            name="has_proxy_bypass",
        ),
    ]
