# Generated by Django 4.2.16 on 2026-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_tariff_has_proxy_bypass"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_provider",
            field=models.CharField(
                choices=[("yoomoney", "YooMoney"), ("platega", "Platega")],
                default="yoomoney",
                max_length=20,
                verbose_name="Платёжный провайдер",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="platega_transaction_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Platega Transaction ID",
            ),
        ),
    ]
