# Generated by Django 4.2.16 on 2026-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_order_payment_provider_order_platega_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="URL оплаты",
            ),
        ),
    ]
