# Generated by Django 4.2.16 on 2026-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_order_payment_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tariff",
            name="change_locked",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Если включено — пользователь с этим "
                    "тарифом не сможет сменить его на другой."
                ),
                verbose_name="Блокировка смены тарифа",
            ),
        ),
    ]
