# Generated by Django 4.2.16 on 2026-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_tariff_change_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "Purchase"),
                    ("TOPUP", "Top-up"),
                    ("WHITELIST_TOPUP", "Whitelist Traffic Top-up"),
                    ("SLOT", "Slot"),
                ],
                default="PURCHASE",
                max_length=20,
            ),
        ),
    ]
