# Generated by Django 4.2.16 on 2026-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_tarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_username",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
