# Generated by Django 4.2.16 on 2026-05-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_order_amount_order_order_type_alter_order_tariff"),
        ("user", "0003_profile_telegram_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="tarif",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.tariff",
            ),
        ),
    ]
