# Generated by Django 4.2.16 on 2026-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_tarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notifications_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="payment_reminder_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Напоминание об оплате"
            ),
        ),
    ]
