# Generated by Django 4.2.16 on 2026-05-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_profile_subscription_expired_notification_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("BALANCE", "Деньги на баланс"),
                            ("DAYS", "Дни к подписке"),
                        ],
                        max_length=10,
                        verbose_name="Тип бонуса",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        verbose_name="Сумма (руб. или дней)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата активации"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создан"
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_promocodes",
                        to="user.profile",
                        verbose_name="Использован пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
    ]
