# Generated by Django 4.2.16 on 2026-05-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_add_promocode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromoCode",
        ),
    ]
