# Generated by Django 4.2.16 on 2026-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_delete_promocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="whitelist_expire_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Whitelist подписка истекает",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="whitelist_traffic_bytes",
            field=models.BigIntegerField(
                default=5368709120,
                help_text="Лимит трафика для whitelist-подписки в байтах",
                verbose_name="Whitelist трафик (байт)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="whitelist_uuid",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Whitelist UUID в Remnawave",
            ),
        ),
    ]
