# Generated by Django 4.2.16 on 2026-07-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_add_whitelist_sub_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="whitelist_expire_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="whitelist_traffic_bytes",
        ),
    ]
