# Generated by Django 4.2.16 on 2026-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_whitelist_local_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="server_notifications_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления о серверах"
            ),
        ),
    ]
