# Generated by Django 4.2.16 on 2026-09-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_profile_telegram_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="Реферальный код",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_earned",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Заработано по рефералам",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referral_reward_paid",
            field=models.BooleanField(
                default=False,
                verbose_name="Реферальная награда выплачена",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="user.profile",
                verbose_name="Пригласил",
            ),
        ),
    ]
